#!/bin/sh

# 1. Weston/Wayland Envionment
export QT_QPA_PLATFORM=wayland
export ELM_ENGINE=wayland_egl
export ECORE_EVAS_ENGINE=wayland_egl
export XDG_CONFIG_HOME=/etc/xdg/weston

# 2. Start Device Input Controller for eGalax TouchPanel
#/usr/bin/ico_ictl-touch_egalax -t
/usr/bin/ico_ictl-touch_egalax
sleep 0.3

# 3 start some daemons
## if pulseaudio dose not start ... kick pulseaudio
/bin/ps ax | /bin/grep pulseaudio | /bin/grep -v grep > /dev/null
if [ "$?" = "1" ] ; then
	/usr/bin/pulseaudio --log-level=3 --log-target=file:/var/log/ico/pulse.log --system -D
	sleep 0.5
fi

## if appcore launcher dose not start ... kick launchpad_preloading_preinitializing_daemon
/bin/ps ax | /bin/grep launchpad_preloading_preinitializing_daemon | /bin/grep -v grep > /dev/null
if [ "$?" = "1" ] ; then
	/usr/bin/launchpad_preloading_preinitializing_daemon &
	sleep 1
fi

# 4 start homescreen
/usr/bin/launch_app org.tizen.ico.homescreen &

