#!/bin/sh

# 1. Delete log file
/bin/mkdir /var/log/ico > /dev/null 2>&1
/bin/chmod -R 0777 /var/log/ico > /dev/null 2>&1
/bin/rm -f /var/log/ico/* /var/log/weston.log > /dev/null 2>&1
/bin/rm -f /opt/share/crash/core.* > /dev/null 2>&1

# 2. Start Device Input Controller for eGalax TouchPanel
#/usr/bin/ico_ictl-touch_egalax -t
/usr/bin/ico_ictl-touch_egalax
sleep 0.3

# 3. Start Weston
/usr/bin/weston-launch --user app -- -i0 --log=/var/log/ico/weston.log &
sync;sync
#sleep 0.8
#if [ -e $XDG_RUNTIME_DIR/wayland-0 ] ; then
#	chmod 0777 $XDG_RUNTIME_DIR/wayland-0
#fi

# 4 start some daemons
## if pulseaudio dose not start ... kick pulseaudio
/bin/ps ax | /bin/grep pulseaudio | /bin/grep -v grep > /dev/null
if [ "$?" = "1" ] ; then
	/usr/bin/pulseaudio --log-level=3 --log-target=file:/var/log/ico/pulse.log --system -D
	sleep 0.5
fi

## if appcore launcher dose not start ... kick launchpad_preloading_preinitializing_daemon
/bin/ps ax | /bin/grep launchpad_preloading_preinitializing_daemon | /bin/grep -v grep > /dev/null
if [ "$?" = "1" ] ; then
	/usr/bin/launchpad_preloading_preinitializing_daemon &
	sleep 1
fi

# 5 start homescreen
export PKG_NAME="org.tizen.ico.homescreen"
/usr/bin/launch_app org.tizen.ico.homescreen &

