#!/bin/sh

# 1. kill pulseaudio and weston, and start pulseaudio
/usr/bin/killall pulseaudio > /dev/null 2>&1
/usr/bin/killall weston > /dev/null 2>&1
/bin/sleep 0.2
/usr/bin/killall -9 pulseaudio > /dev/null 2>&1
/usr/bin/killall -9 weston > /dev/null 2>&1

# 2. Delete log file
/bin/mkdir /var/log/ico > /dev/null 2>&1
/bin/chmod -R 0777 /var/log/ico > /dev/null 2>&1
/bin/rm -f /var/log/ico/* /var/log/weston.log > /dev/null 2>&1
/bin/rm -f /opt/bs/core/* > /dev/null 2>&1

# 3. Weston/Wayland Envionment
export XDG_RUNTIME_DIR=/tmp/run-root
export QT_QPA_PLATFORM=wayland
export ELM_ENGINE=wayland_egl
export ECORE_EVAS_ENGINE=wayland_egl
#export ELM_ENGINE=wayland_shm
#export ECORE_EVAS_ENGINE=wayland_shm
export EVAS_FONT_DPI=72
export ECORE_IMF_MODULE=isf
export ELM_MODULES="ctxpopup_copypasteUI>entry/api:datetime_input_ctxpopup>datetime/api"
export ELM_SCALE="0.7"
export ELM_PROFILE=mobile

# 4. Start Device Input Controller for eGalax TouchPanel
#/usr/bin/ico_ictl-touch_egalax -t
/usr/bin/ico_ictl-touch_egalax
sleep 0.3

# 5. Start Weston
ORG_UMASK=`umask`
umask 000
/usr/bin/weston --backend=drm-backend.so --idle-time=0 --log=/var/log/weston.log &
sync;sync
sleep 0.8
if [ -f $XDG_RUNTIME_DIR/wayland-0 ] ; then
	chmod 0777 $XDG_RUNTIME_DIR/wayland-0
fi
umask $ORG_UMASK

## if pulseaudio dose not start ... kick pulseaudio
/bin/ps ax | /bin/grep pulseaudio | /bin/grep -v grep > /dev/null
if [ "$?" = "1" ] ; then
	/usr/bin/pulseaudio --log-level=3 --log-target=file:/var/log/ico/pulse.log --system -D
	sleep 0.5
fi

# 5 start sample wayland client for display cursor
sync;sync
/usr/bin/nice -19 /usr/bin/wayland-smoke &
sleep 0.3

# 6 start app core daemon
/bin/ps ax | /bin/grep launchpad_preloading_preinitializing_daemon | /bin/grep -v grep > /dev/null
if [ "$?" = "1" ] ; then
	/usr/bin/launchpad_preloading_preinitializing_daemon &
	sleep 1
fi

# 7 start homescreen
/usr/bin/launch_app org.tizen.ico.homescreen &

