#! /bin/sh
# Provides:          ico_uxf_HomeScreen
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Homescreen boot script for ico-ivi
# Description:       This script starts the Weston compositor and ico-uxf-HomeScreen at boot.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="ICO UXF Home Screen"
NAME=ico_uxf_HomeScreen
DAEMON=/usr/bin/launch_app
DAEMON_ARGS="org.tizen.ico.homescreen"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
export HOME="/opt/home/root"

ICO_LOG_DIR=/var/log/ico

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
		|| return 1
	
	# make and clean log directory
	if [ ! -d "${ICO_LOG_DIR}" ]; then
	    mkdir -p $ICO_LOG_DIR
	fi

	/bin/chmod -R 0777 /var/log/ico
	/bin/rm -f /var/log/ico/*
	
	# kill pulseaudio and weston, and start pulseaudio
	/usr/bin/killall pulseaudio > /dev/null 2>&1
	/etc/init.d/weston stop > /dev/null 2>&1
	/bin/sleep 0.2
	/usr/bin/killall -9 pulseaudio > /dev/null 2>&1
	/usr/bin/killall -9 weston > /dev/null 2>&1

	# Start Device Input Controller for eGalax TouchPanel
	#/usr/bin/ico_ictl-touch_egalax -t
	/usr/bin/ico_ictl-touch_egalax
	
	# re-load launchpad
	/bin/ps ax | /bin/grep launchpad_preloading | /bin/grep -v grep > /dev/null
	if [ "$?" = "0" ] ; then
		/usr/bin/killall launchpad_preloading_preinitializing_daemon
		/bin/sleep 0.3
	fi
	/usr/bin/launchpad_preloading_preinitializing_daemon &

	# Start weston
	/etc/init.d/weston start

	# Start wayland-client for display mouse cursor
	#/usr/bin/nice -19 /usr/bin/wayland-smoke &

	## if pulseaudio does not start ... kick pulseaudio
	/bin/ps ax | /bin/grep pulseaudio | /bin/grep -v grep > /dev/null
	if [ "$?" = "1" ] ; then
		/usr/bin/pulseaudio --log-level=3 --log-target=file:/var/log/ico/pulse.log --system -D
    		/bin/sleep 0.2
	fi

	# Start HomeScreen
	/bin/sleep 0.5
	/usr/bin/killall menu-screen
	/usr/bin/killall menu-daemon
	/usr/bin/pmctrl stop

	# start-stop-daemon --start --background --quiet --pidfile $PIDFILE --exec $DAEMON -- \
	#	$DAEMON_ARGS \
	#	|| return 2
	$DAEMON $DAEMON_ARGS &
	homescreen_pid=$!
	/bin/sleep 0.2

	if [ $homescreen_pid = 0 ]; then
	    return 2
	else
	    echo $homescreen_pid > $PIDFILE
	fi

	# Add code here, if necessary, that waits for the process to be ready
	# to handle requests from services started subsequently which depend
	# on this one.  As a last resort, sleep for some time.
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	#start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
	start-stop-daemon --stop --quiet --pidfile $PIDFILE --name $NAME
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2
	# Wait for children to finish too if this is a daemon that forks
	# and if the daemon is only ever run from this initscript.
	# If the above conditions are not satisfied then add some other code
	# that waits for the process to drop all resources that could be
	# needed by services started subsequently.  A last resort is to
	# sleep for some time.
	#start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
	start-stop-daemon --stop --quiet --oknodo --exec $DAEMON
	[ "$?" = 2 ] && return 2
	# Many daemons don't delete their pidfiles when they exit.
	rm -f $PIDFILE

	# Stop Weston.
	/etc/init.d/weston stop

	return "$RETVAL"
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	#
	# If the daemon can reload its configuration without
	# restarting (for example, when it is sent a SIGHUP),
	# then implement that here.
	#
	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
	return 0
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
       ;;
  #reload|force-reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	#log_daemon_msg "Reloading $DESC" "$NAME"
	#do_reload
	#log_end_msg $?
	#;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
