#!/bin/bash

rm -rf \
Makefile \
Makefile.am~ \
Makefile.in \
aclocal.m4 \
autom4te.cache \
config.guess \
config.h \
config.h.in \
config.h.in~ \
config.log \
config.status \
config.sub \
configure \
depcomp \
install-sh \
libtool \
ltmain.sh \
missing \
stamp-h1 \
./lib/Makefile \
./lib/Makefile.in \
./lib/common/.deps \
./lib/common/Makefile \
./lib/common/Makefile.in \
./lib/system-controller/.deps \
./lib/system-controller/Makefile \
./lib/system-controller/Makefile.in \
./lib/notification/.deps \
./lib/notification/Makefile \
./lib/notification/Makefile.in \
./lib/apps-framework/.deps \
./lib/apps-framework/Makefile \
./lib/apps-framework/Makefile.in \
./lib/misc/Makefile \
./lib/misc/Makefile.in \
./lib/misc/state-machine/.deps \
./lib/misc/state-machine/Makefile \
./lib/misc/state-machine/Makefile.in \
./lib/misc/log/.deps \
./lib/misc/log/Makefile \
./lib/misc/log/Makefile.in \
./src/Makefile \
./src/Makefile.in \
./src/system-controller/.deps \
./src/homescreen/.deps \
./src/homescreen/Makefile \
./src/homescreen/Makefile.in \
./src/statusbar/.deps \
./src/statusbar/Makefile \
./src/statusbar/Makefile.in \
./src/onscreen/.deps \
./src/onscreen/Makefile \
./src/onscreen/Makefile.in \
./src/syscond/.deps \
./src/syscond/Makefile \
./src/syscond/Makefile.in \
./tests/Makefile \
./tests/Makefile.in \
./tests/statusbar/.deps \
./tests/statusbar/Makefile \
./tests/statusbar/Makefile.in \
./tests/system-controller/Makefile \
./tests/system-controller/Makefile.in \
./tests/system-controller/apps-framework/result \
./tests/system-controller/apps-framework/.deps \
./tests/system-controller/apps-framework/Makefile \
./tests/system-controller/apps-framework/Makefile.in \
./tests/system-controller/system-controller/.deps \
./tests/system-controller/system-controller/Makefile \
./tests/system-controller/system-controller/Makefile.in \
./tests/system-controller/test-dummy-hs/.deps \
./tests/system-controller/test-dummy-hs/Makefile \
./tests/system-controller/test-dummy-hs/Makefile.in \
./tool/.deps \
./tool/Makefile \
./tool/Makefile.in \
./tool/notification/Makefile \
./tool/notification/Makefile.in
