#!/bin/bash

rm -rf \
Makefile \
Makefile.am~ \
Makefile.in \
aclocal.m4 \
autom4te.cache \
config.guess \
config.h \
config.h.in \
config.h.in~ \
config.log \
config.status \
config.sub \
configure \
depcomp \
install-sh \
libtool \
ltmain.sh \
missing \
stamp-h1 \
./lib/Makefile \
./lib/Makefile.in \
./lib/common/.deps \
./lib/common/Makefile \
./lib/common/Makefile.in \
./lib/notification/.deps \
./lib/notification/Makefile \
./lib/notification/Makefile.in \
./lib/misc/Makefile \
./lib/misc/Makefile.in \
./lib/misc/log/.deps \
./lib/misc/log/Makefile \
./lib/misc/log/Makefile.in \
./src/Makefile \
./src/Makefile.in \
./src/homescreen/.deps \
./src/homescreen/Makefile \
./src/homescreen/Makefile.in \
./src/statusbar/.deps \
./src/statusbar/Makefile \
./src/statusbar/Makefile.in \
./src/onscreen/.deps \
./src/onscreen/Makefile \
./src/onscreen/Makefile.in \
./tests/Makefile \
./tests/Makefile.in \
./tests/statusbar/.deps \
./tests/statusbar/Makefile \
./tests/statusbar/Makefile.in
